#!/usr/bin/env python3
"""Convert Crazy-Sensei opening book JSON into a C++ initializer list.

Reads the curated opening book from Book/.../harness_openings_curated.json
and emits src/engine/OpeningBookData.inc. Each opening of length N is
expanded into N entries mapping prefix[0..k-1] -> move[k] for k in 0..N-1.
Entries are canonicalised under the 8-fold D4 symmetry group of the board
and deduplicated, so rotations and reflections of the same position
collapse to one entry (the engine re-applies symmetries at lookup time).
"""

from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from pathlib import Path

BOARD_SIZE = 15

# Move is (row, col). Wire convention from the JSON is (y=row, x=col).


def sym_identity(r, c, n):
    return r, c


def sym_rot90(r, c, n):
    return c, n - 1 - r


def sym_rot180(r, c, n):
    return n - 1 - r, n - 1 - c


def sym_rot270(r, c, n):
    return n - 1 - c, r


def sym_mirror_v(r, c, n):
    return r, n - 1 - c


def sym_mirror_h(r, c, n):
    return n - 1 - r, c


def sym_mirror_main(r, c, n):
    return c, r


def sym_mirror_anti(r, c, n):
    return n - 1 - c, n - 1 - r


SYMMETRIES = [
    sym_identity,
    sym_rot90,
    sym_rot180,
    sym_rot270,
    sym_mirror_v,
    sym_mirror_h,
    sym_mirror_main,
    sym_mirror_anti,
]


def canonical(prefix, move):
    """Return lex-min transform of (prefix + [move]) under D4.

    The canonicalisation keys on the prefix first, then on the move,
    so entries with the same prefix shape share a symmetry choice.
    """
    best = None
    for sym in SYMMETRIES:
        transformed_prefix = tuple(sym(r, c, BOARD_SIZE) for r, c in prefix)
        transformed_move = sym(move[0], move[1], BOARD_SIZE)
        key = (transformed_prefix, transformed_move)
        if best is None or key < best:
            best = key
    return best


@dataclass(frozen=True)
class Entry:
    prefix: tuple
    move: tuple


def load_openings(path: Path):
    with path.open("r", encoding="utf-8") as f:
        data = json.load(f)
    openings = data["openings"]
    for opening in openings:
        moves = [(m["y"], m["x"]) for m in opening["moves"]]
        yield moves


def expand_to_entries(openings):
    seen = set()
    entries = []
    for moves in openings:
        for k in range(len(moves)):
            prefix = tuple(moves[:k])
            move = moves[k]
            canon_prefix, canon_move = canonical(prefix, move)
            key = (canon_prefix, canon_move)
            if key in seen:
                continue
            seen.add(key)
            entries.append(Entry(canon_prefix, canon_move))
    # Sort by prefix length (shorter first), then lexicographically for
    # deterministic output.
    entries.sort(key=lambda e: (len(e.prefix), e.prefix, e.move))
    return entries


def format_move(row, col):
    return f"{{{row}, {col}}}"


def format_entry(index: int, entry: Entry) -> str:
    line_name = f"cs{index:04d}"
    prefix_parts = ", ".join(f"moveAction({format_move(r, c)})" for r, c in entry.prefix)
    prefix_literal = f"{{{prefix_parts}}}"
    move_literal = format_move(entry.move[0], entry.move[1])
    return (
        f'    {{Ruleset::Freestyle15, "{line_name}", '
        f"{prefix_literal}, {move_literal}}},"
    )


def emit(entries, source_file: Path, output_path: Path):
    lines = [
        "// Auto-generated by scripts/convert_opening_book.py.",
        "// Do not edit by hand; re-run the converter to refresh.",
        f"// Source: {source_file.as_posix()}",
        f"// Entries: {len(entries)}",
        "",
    ]
    for i, entry in enumerate(entries, start=1):
        lines.append(format_entry(i, entry))
    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--source",
        type=Path,
        default=Path("Book/crazy_sensei_gomoku_15x15_depth8_full/harness_openings_curated.json"),
        help="Path to the curated JSON (relative to repo root).",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("src/engine/OpeningBookData.inc"),
        help="Destination C++ include file.",
    )
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=Path(__file__).resolve().parent.parent,
        help="Repository root (defaults to the parent of scripts/).",
    )
    args = parser.parse_args()

    source = args.repo_root / args.source
    output = args.repo_root / args.output
    output.parent.mkdir(parents=True, exist_ok=True)

    openings = list(load_openings(source))
    entries = expand_to_entries(openings)
    emit(entries, args.source, output)
    print(f"Wrote {len(entries)} entries to {output}")


if __name__ == "__main__":
    main()
